name: 'Build and Push Docker to ACR'
description: 'Build a Dockerfile and upload the resulting image to an Azure Container Registry.'
inputs:
  dockerfile:
    description: 'Path to the Dockerfile'
    required: true
    default: './Dockerfile'
  context:
    description: 'Context for building the Docker image'
    required: true
    default: '.'
  image_name:
    description: 'Name of the Docker image'
    required: true
  acr_login_server:
    description: 'Azure Container Registry login server'
    required: true
  acr_username:
    description: 'Azure Service Principal or ACR username'
    required: true
  acr_password:
    description: 'Azure Service Principal password or ACR password'
    required: true
  tag:
    description: 'The tag with which to tag the image'
    required: false
    default: ${{ github.sha }}

runs:
  using: 'composite'
  steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      run: |
        echo "${{ inputs.acr_password }}" | docker login ${{ inputs.acr_login_server }} -u ${{ inputs.acr_username }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -f ${{ inputs.dockerfile }} -t ${{ inputs.image_name }}:${{ github.sha }} ${{ inputs.context }}

    - name: Push Docker image to ACR
      run: |
        docker tag ${{ inputs.image_name }}:${{ inputs.tag }} ${{ inputs.acr_login_server }}/${{ inputs.image_name }}:${{ github.sha }}
        docker push ${{ inputs.acr_login_server }}/${{ inputs.image_name }}:${{ nputs.tag }}
